name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npx eslint .

      - name: Run Tests
        run: npm test  # Add tests before enabling this step

      - name: Build the package
        run: npm pack

      - name: Publish to JFrog Artifactory
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          curl -u $JFROG_USER:$JFROG_PASSWORD -T motivator-cli-1.0.0.tgz "https://trial9czqrt.jfrog.io/ui/packages/artifactory/npm-repo/motivator-cli-1.0.0.tgz"

